import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from "./provider";
import { ReactQueryProviders } from "@/provider/ReactQuerryProvider";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Đấu giá biển số xe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ReactQueryProviders>
          <div className="bg-[#475657] w-full min-h-screen"><Navbar />
          {children}</div>
          </ReactQueryProviders></Providers>
      </body>
    </html>
  );
}
